In [9]:
import glob

import numpy as np

import librosa


from sklearn.model_selection import train_test_split

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler


import os
import pickle
import warnings
from sklearn import preprocessing
from scipy.io.wavfile import read
import python_speech_features as mfcc
from sklearn.mixture import GaussianMixture 
from sklearn.metrics import f1_score
import joblib

In [10]:
# def calculate_delta(array):
   
#     rows, cols = array.shape
#     # print(rows)
#     # print(cols)
#     deltas = np.zeros((rows,20))
#     N = 2
#     for i in range(rows):
#         index = []
#         j = 1
        
#         while j <= N:
#             if i-j < 0:
#                 first =0
#             else:
#                 first = i-j
#             if i+j > rows-1:
#                 second = rows-1
#             else:
#                 second = i+j 
#             index.append((second,first))
#             j+=1
#         deltas[i] = ( array[index[0][0]]-array[index[0][1]] + (2 * (array[index[1][0]]-array[index[1][1]])) ) / 10
#     return deltas
def remove_noise(data):
    data= librosa.effects.preemphasis(data)
    return data
def extract_features(data,sr):
    mfcc= librosa.feature.mfcc(y= data,sr=sr,n_mfcc=30)  
    #print(mfcc.shape) 
    delta = librosa.feature.delta(mfcc)
    #print(delta.shape)
    delta_2 = librosa.feature.delta(delta)
    #Combine MFCC and Delta features
    combined_feat = np.concatenate((mfcc,delta,delta_2))
    #features.append(combined_feat.T)
    return combined_feat.T
    #print(features)


# def extract_features(audio,rate):
       
#     mfcc_feature = mfcc.mfcc(audio, rate, 0.025, 0.01, 20, nfft = 2205, appendEnergy = True)    
#     mfcc_feature = preprocessing.scale(mfcc_feature)
# #     print(mfcc_feature)
#     delta = calculate_delta(mfcc_feature)
#     combined = np.hstack((mfcc_feature, delta)) 
#     return combined

In [11]:
feature = []
y_test = []
import soundfile as sf


lstFolders = ['manar', 'salma', 'sara','yasmeen','others']
for lst in lstFolders:
    listFiles = glob.glob(r"./speak_data/{}\*".format(lst))
    features = np.asarray(())
    finishCounter = len(listFiles)
    counter = 1
    for file in listFiles:
        try:
            audio, sr = librosa.load(file)
            vector = extract_features(audio, sr)
            
            if features.size == 0:
                features = vector
            else:
                features = np.vstack((features, vector))
                
            feature.append(vector)
            y_test.append(lstFolders.index(lst))
            #print(feature)
                
            counter += 1
            if(counter == finishCounter):
                gmm = GaussianMixture(n_components = 7, max_iter = 200, covariance_type='diag', n_init = 3)
                gmm.fit(features)
                
                # dumping the trained gaussian model
                picklefile = lst + ".joblib1"
                joblib.dump(gmm, picklefile) 
                print(picklefile)
        except  Exception as e:
            print("An error occurred:", e)


manar.joblib1
salma.joblib1
sara.joblib1
yasmeen.joblib1
others.joblib1


In [12]:
print(y_test)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 

In [13]:
gmm_files = [ i + '.joblib1' for i in ['manar', 'salma', 'sara','yasmeen','others']]

models    = [joblib.load(fname) for fname in gmm_files]
speakers   = [fname.split("\\")[-1].split(".joblib")[0] for fname 
                  in gmm_files]

In [14]:
labels = []
y = []
for i in feature:
    log_likelihood = np.zeros(len(models)) 
    for j in range(len(models)):
        gmm = models[j] 
        scores = np.array(gmm.score(i))
        print(scores)
        print("hhhhhhhhh")
        log_likelihood[j] = scores.sum()
    y.append(log_likelihood)
    #print(y)
    print("..............")
    winner = np.argmax(log_likelihood)
    print("\tdetected as - ", speakers[winner])
    labels.append(winner)
    print(labels)

-135.03609171338684
hhhhhhhhh
-143.60287892734715
hhhhhhhhh
-145.95952679272108
hhhhhhhhh
-142.96178006233404
hhhhhhhhh
-154.33313034098887
hhhhhhhhh
..............
	detected as -  manar
[0]
-173.81546139141022
hhhhhhhhh
-193.633296036124
hhhhhhhhh
-197.36812876544113
hhhhhhhhh
-187.82807365137677
hhhhhhhhh
-197.41131807058758
hhhhhhhhh
..............
	detected as -  manar
[0, 0]
-166.48567564589993
hhhhhhhhh
-191.14651233417771
hhhhhhhhh
-188.27703046807403
hhhhhhhhh
-180.70733392501285
hhhhhhhhh
-191.26600348302802
hhhhhhhhh
..............
	detected as -  manar
[0, 0, 0]
-169.65224293727152
hhhhhhhhh
-189.32078228957437
hhhhhhhhh
-189.72994169929868
hhhhhhhhh
-183.00599181675594
hhhhhhhhh
-194.75945220266067
hhhhhhhhh
..............
	detected as -  manar
[0, 0, 0, 0]
-167.45441308911293
hhhhhhhhh
-193.1760979199574
hhhhhhhhh
-197.84692928819854
hhhhhhhhh
-188.0588544402441
hhhhhhhhh
-195.4137046123828
hhhhhhhhh
..............
	detected as -  manar
[0, 0, 0, 0, 0]
-173.72469458264396


In [15]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(labels, y_test)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 99.01


In [16]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(labels, y_test)
print('Confusion Matrix: \n', cm)

Confusion Matrix: 
 [[80  0  0  0  2]
 [ 0 80  0  0  0]
 [ 0  0 80  0  0]
 [ 0  0  0 80  2]
 [ 0  0  0  0 82]]
